# Generated by Django 2.2.2 on 2019-08-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_nomenclature_sid", models.CharField(max_length=10)),
                ("productline_suffix", models.CharField(max_length=2)),
                ("leaf", models.BooleanField()),
                ("parent_goods_nomenclature_item_id", models.CharField(max_length=10)),
                ("parent_goods_nomenclature_sid", models.CharField(max_length=10)),
                ("parent_productline_suffix", models.CharField(max_length=2)),
                ("description", models.TextField()),
                ("number_indents", models.SmallIntegerField()),
                ("keywords", models.TextField(blank=True, null=True)),
                ("ranking", models.SmallIntegerField(blank=True, null=True)),
                ("chapter_code", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Heading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_nomenclature_sid", models.CharField(max_length=10)),
                ("productline_suffix", models.CharField(max_length=2)),
                ("leaf", models.BooleanField()),
                ("parent_goods_nomenclature_item_id", models.CharField(max_length=10)),
                ("parent_goods_nomenclature_sid", models.CharField(max_length=10)),
                ("parent_productline_suffix", models.CharField(max_length=2)),
                ("description", models.TextField()),
                ("number_indents", models.SmallIntegerField()),
                ("keywords", models.TextField(blank=True, null=True)),
                ("ranking", models.SmallIntegerField(blank=True, null=True)),
                ("heading_code", models.CharField(max_length=10)),
                (
                    "heading_code_4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("tts_json", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headings",
                        to="hierarchy.Chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.IntegerField(unique=True)),
                ("tts_json", models.TextField(blank=True)),
                ("roman_numeral", models.CharField(max_length=5)),
                ("title", models.TextField()),
                ("position", models.IntegerField()),
                ("keywords", models.TextField(null=True)),
                ("ranking", models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hierarchy.Section",
            ),
        ),
        migrations.CreateModel(
            name="SubHeading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productline_suffix", models.CharField(max_length=2)),
                ("parent_goods_nomenclature_item_id", models.CharField(max_length=10)),
                ("parent_goods_nomenclature_sid", models.CharField(max_length=10)),
                ("parent_productline_suffix", models.CharField(max_length=2)),
                ("description", models.TextField()),
                ("number_indents", models.SmallIntegerField()),
                ("keywords", models.TextField(blank=True, null=True)),
                ("ranking", models.SmallIntegerField(blank=True, null=True)),
                ("commodity_code", models.CharField(max_length=10)),
                ("goods_nomenclature_sid", models.CharField(max_length=10)),
                ("tts_is_leaf", models.BooleanField()),
                (
                    "heading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_subheadings",
                        to="hierarchy.Heading",
                    ),
                ),
                (
                    "parent_subheading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_subheadings",
                        to="hierarchy.SubHeading",
                    ),
                ),
            ],
            options={"unique_together": {("commodity_code", "description")}},
        ),
    ]
