# Generated by Django 2.1.5 on 2019-03-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_nomenclature_sid', models.CharField(max_length=10, null=True)),
                ('productline_suffix', models.CharField(max_length=2, null=True)),
                ('leaf', models.BooleanField(blank=True, null=True)),
                ('parent_goods_nomenclature_item_id', models.CharField(max_length=10, null=True)),
                ('parent_goods_nomenclature_sid', models.CharField(max_length=10, null=True)),
                ('parent_productline_suffix', models.CharField(max_length=2, null=True)),
                ('description', models.TextField(null=True)),
                ('number_indents', models.SmallIntegerField(null=True)),
                ('chapter_code', models.CharField(max_length=30)),
                ('tts_json', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_nomenclature_sid', models.CharField(max_length=10, null=True)),
                ('productline_suffix', models.CharField(max_length=2, null=True)),
                ('leaf', models.BooleanField(blank=True, null=True)),
                ('parent_goods_nomenclature_item_id', models.CharField(max_length=10, null=True)),
                ('parent_goods_nomenclature_sid', models.CharField(max_length=10, null=True)),
                ('parent_productline_suffix', models.CharField(max_length=2, null=True)),
                ('description', models.TextField(null=True)),
                ('number_indents', models.SmallIntegerField(null=True)),
                ('heading_code', models.CharField(max_length=10)),
                ('heading_code_4', models.CharField(blank=True, max_length=4, null=True)),
                ('tts_json', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='hierarchy.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField(unique=True)),
                ('tts_json', models.TextField(blank=True, null=True)),
                ('roman_numeral', models.CharField(max_length=5, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productline_suffix', models.CharField(max_length=2, null=True)),
                ('parent_goods_nomenclature_item_id', models.CharField(max_length=10, null=True)),
                ('parent_goods_nomenclature_sid', models.CharField(max_length=10, null=True)),
                ('parent_productline_suffix', models.CharField(max_length=2, null=True)),
                ('description', models.TextField(null=True)),
                ('number_indents', models.SmallIntegerField(null=True)),
                ('commodity_code', models.CharField(max_length=10)),
                ('goods_nomenclature_sid', models.CharField(max_length=10)),
                ('tts_heading_json', models.TextField(blank=True, null=True)),
                ('tts_is_leaf', models.BooleanField(blank=True, null=True)),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_subheadings', to='hierarchy.Heading')),
                ('parent_subheading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_subheadings', to='hierarchy.SubHeading')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='subheading',
            unique_together={('commodity_code', 'goods_nomenclature_sid')},
        ),
    ]
