# Generated by Django 2.1.5 on 2019-03-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20190308_1155'),
        ('hierarchy', '0002_auto_20190301_0956'),
    ]

    operations = [
    ]
