# Generated by Django 2.2.5 on 2019-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_subheading_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='subheading',
            name='tts_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
