# Generated by Django 2.1.5 on 2019-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20190312_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='goods_nomenclature_sid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='leaf',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='number_indents',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_goods_nomenclature_item_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_goods_nomenclature_sid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='goods_nomenclature_sid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='leaf',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='number_indents',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='parent_goods_nomenclature_item_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='parent_goods_nomenclature_sid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='parent_productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='roman_numeral',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subheading',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subheading',
            name='number_indents',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subheading',
            name='parent_goods_nomenclature_item_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subheading',
            name='parent_goods_nomenclature_sid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subheading',
            name='parent_productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subheading',
            name='productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='heading_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='heading',
            name='heading_code_4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
