# Generated by Django 2.1.5 on 2019-03-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20190310_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='heading_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='heading',
            name='heading_code_4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
