# Generated by Django 2.1.5 on 2019-04-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20190314_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subheading',
            unique_together={('commodity_code', 'description')},
        ),
    ]
