# Generated by Django 2.2.6 on 2019-12-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hierarchy", "0004_auto_20191114_0910")]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="tts_json",
            field=models.TextField(blank=True, null=True),
        )
    ]
