# Generated by Django 2.1.5 on 2019-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_auto_20190423_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='keyword',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heading',
            name='keyword',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='keyword',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subheading',
            name='keyword',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
