# Generated by Django 2.1.5 on 2019-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0005_auto_20190528_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='ranking_score',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heading',
            name='ranking_score',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='ranking_score',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subheading',
            name='ranking_score',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
