# Generated by Django 2.1.5 on 2019-05-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_auto_20190528_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='ranking_score',
            new_name='ranking',
        ),
        migrations.RenameField(
            model_name='heading',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='heading',
            old_name='ranking_score',
            new_name='ranking',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='ranking_score',
            new_name='ranking',
        ),
        migrations.RenameField(
            model_name='subheading',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='subheading',
            old_name='ranking_score',
            new_name='ranking',
        ),
    ]
