# Generated by Django 2.1.5 on 2019-06-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0007_auto_20190529_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='ranking',
            field=models.SmallIntegerField(null=True),
        ),
    ]
