# Generated by Django 2.1.5 on 2019-06-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0008_auto_20190603_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='ranking',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='ranking',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subheading',
            name='ranking',
            field=models.SmallIntegerField(null=True),
        ),
    ]
