# Generated by Django 2.2.13 on 2020-09-10 15:50
import django_migration_linter as linter

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hierarchy", "0009_auto_20200908_2043")]

    operations = [
        linter.IgnoreMigration(),
        migrations.AlterField(
            model_name="section", name="section_id", field=models.IntegerField()
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("section_id", "nomenclature_tree"), name="unique section"
            ),
        ),
    ]
