# Generated by Django 2.2.2 on 2019-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0009_auto_20190603_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='tts_json',
        ),
        migrations.AddField(
            model_name='heading',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
