# Generated by Django 2.2.2 on 2019-08-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0010_auto_20190806_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subheading',
            name='tts_heading_json',
        ),
    ]
