# Generated by Django 2.2.2 on 2019-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0011_remove_subheading_tts_heading_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='roman_numeral',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(),
        ),
    ]
