# Generated by Django 2.2.2 on 2019-08-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0012_auto_20190814_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='tts_json',
        ),
        migrations.AlterField(
            model_name='section',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
