# Generated by Django 2.2.13 on 2020-10-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0013_auto_20201005_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='subheading',
            name='last_updated',
        ),
    ]
