# Generated by Django 2.2.13 on 2020-10-05 16:20
import django_migration_linter as linter

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("hierarchy", "0013_auto_20201009_1708")]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(model_name="chapter", name="tts_json"),
        migrations.RemoveField(model_name="heading", name="tts_json"),
        migrations.RemoveField(model_name="section", name="tts_json"),
        migrations.RemoveField(model_name="subheading", name="tts_json"),
    ]
