# Generated by Django 2.2.2 on 2019-08-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0013_auto_20190815_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
