# Generated by Django 2.2.13 on 2020-10-06 12:21
import django_migration_linter as linter

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("hierarchy", "0015_remove_last_updated")]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(model_name="chapter", name="last_updated"),
    ]
