# Generated by Django 2.2.13 on 2020-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0016_remove_chapter_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclaturetree',
            name='source',
            field=models.CharField(default='original', max_length=255),
        ),
    ]
