# Generated by Django 2.2.24 on 2021-07-06 13:34

from django.db import migrations, models
import django.db.models.deletion
import hierarchy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hierarchy", "0017_nomenclaturetree_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="RulesOfOriginMixinModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hierarchy.Chapter",
                    ),
                ),
            ],
            bases=(models.Model, hierarchy.models.RulesOfOriginMixin),
        ),
    ]
