
import re

def fhtml(s):
    s = s.replace("<SUBNOTE>", "")
    s = s.replace(' width=\\"*\\"', ''""'')
    s = s.replace(" border=\"0\"", "")
    s = s.replace(' class=\\"rooimpnote\\"', '')
    s = s.replace(' border=\\"0\\"', '')
    s = s.replace(' width=\\"100%\\"', '')
    s = s.replace(' align=\\"center\\"', '')
    s = s.replace(' bgcolor=\\"#FFFFFF\\"', '')
    s = s.replace('\\r\\n', ' ')
    s = s.replace(' valign=top', '')
    s = s.replace(' valign=\\"top\\"', '')
    s = re.sub(' width=[0-9]{1,5}%', '', s)
    s = re.sub(r' width=\\"\d{1,5}%\\"', '', s)
    s = re.sub(r' width=\\"\d{1,5}\\"', '', s)
    s = s.replace(' class=note', '')
    s = s.replace(' border=0', '')
    s = re.sub(r' class=\\"\w{1,20}\\"', '', s)
    s = re.sub(r' id=\\"\w{1,20}\\"', '', s)
    s = re.sub(' class=\w{1,20}([ >])', r'\1', s)
    s = s.replace(' VALIGN=\\"TOP\\"', '')
    s = s.replace(' target=\\"_top\\"', '')
    s = re.sub('<a name=note_[0-9]{1,5}></a>', '', s)
    s = re.sub('< width=[0-9]{1,3}%', '', s)
    s = s.replace('<div>', '')
    s = s.replace('</div>', '')
    s = s.replace('<CHAPTER>', '')
    s = s.replace('</CHAPTER>', '')
    s = s.replace('<td><td>', '<td>')
    s = s.replace('</td></td>', '</td>')
    s = s.replace(r'\t', '')
    s = s.replace('COLSPAN', 'colspan')
    s = s.replace('ROWSPAN', 'rowspan')
    s = s.replace('<TR', '<tr')
    s = s.replace('<TD', '<td')
    s = s.replace('</TR', '</tr')
    s = s.replace('</TD', '</td')
    s = s.replace(' target=new_window', '')
    s = s.replace(' target=new_form', '')
    s = s.replace(' target=oj', '')
    s = s.replace('', '')
    s = s.replace('', '')
    s = s.replace('', '')
    s = s.replace('', '')
    s = s.replace('', '')
    s = s.replace('', '')
    s = re.sub(' {1,10}', ' ', s)
    s = s.replace(' >', '>')
    s = s.replace('> ', '>')
    s = s.replace('< ', '<')
    s = s.strip('"')
    return (s)


def mclean(s):
    s = s.replace('"', '')
    return (s)