# Generated by Django 2.2.13 on 2020-12-16 16:55

from django.db import migrations

from flags.models import FlagState


def create_flags(apps, schema_editor):

    FlagState.objects.create(
        name='PRE21',
        condition='boolean',
        value='True',
    )

    FlagState.objects.create(
        name='JAPAN_FTA',
        condition='boolean',
        value='True',
    )

    FlagState.objects.create(
        name='NI_JOURNEY',
        condition='boolean',
        value='False',
    )


def delete_flags(apps, schema_editor):
    FlagState.objects.filter(
        name__in=['PRE21', 'JAPAN_FTA', 'NI_JOURNEY']
    ).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0013_add_required_field')
    ]

    operations = [
        migrations.RunPython(create_flags, reverse_code=delete_flags)
    ]
