# Generated by Django 2.2.13 on 2020-12-18 14:03

from django.db import migrations


def add_flag(apps, schema_editor):
    FlagState = apps.get_model("flags", "FlagState")

    FlagState.objects.create(
        name="EU_FALLBACK",
        condition="boolean",
        value="False",
    )


def delete_flag(apps, schema_editor):
    FlagState = apps.get_model("flags", "FlagState")

    FlagState.objects.get("EU_FALLBACK").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_flags'),
    ]

    operations = [
        migrations.RunPython(add_flag, reverse_code=delete_flag)
    ]
