# Generated by Django 2.2.13 on 2020-12-30 14:09

from django.db import migrations


def add_flag(apps, schema_editor):
    FlagState = apps.get_model("flags", "FlagState")

    FlagState.objects.create(name="TREE_PRELOAD", condition="boolean", value="False")


def delete_flag(apps, schema_editor):
    FlagState = apps.get_model("flags", "FlagState")

    FlagState.objects.get("TREE_PRELOAD").delete()


class Migration(migrations.Migration):

    dependencies = [("core", "0002_add_eu_fallback_flag")]

    operations = [migrations.RunPython(add_flag, reverse_code=delete_flag)]
