# Generated by Django 2.2.24 on 2021-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_remove_flags_post_transition"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReloadDataTracking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField),
                ("end_time", models.DateTimeField(null=True)),
                ("run_time", models.DurationField(null=True)),
            ],
        ),
    ]
