# Generated by Django 2.2.24 on 2021-11-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_reloaddatatracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="reloaddatatracking",
            name="reason",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
