SUBJECT = "New UK Trade Helpdesk Enquiry"
SERVICE_NAME = "EU Exit"
DIT_SUBDOMAIN = "dit"
DIT_SUBJECT_SUFFIX = " - DIT EU Exit Enquiries"
DDAT_SUBJECT_SUFFIX = " - DDAT Support Team"
FEEDBACK_EMAIL = ""
FEEDBACK_FULLNAME = ""
HMRC_TAX_FORM_URL = "https://www.tax.service.gov.uk/shortforms/form/CITEX_CGEF"
