# Generated by Django 2.2.13 on 2020-09-08 12:57

import csv
import os

from django.db import migrations

from . import DATA_DIR


def update_countries(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    register_file_path = os.path.join(DATA_DIR, "gov-registers-country-2020-09-08.csv")
    register_countries = {}
    with open(register_file_path) as register_country_file:
        reader = csv.DictReader(register_country_file)

        for row in reader:
            try:
                country = Country.objects.get(country_code=row["key"])
            except Country.DoesNotExist:
                continue

            if country.name == row["name"]:
                continue

            country.name = row["name"]
            country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            update_countries,
            migrations.RunPython.noop,
        ),
    ]
