# Generated by Django 2.2.13 on 2020-11-19 14:50

from django.db import migrations

import logging


trade_data = [
    {
        "Country code": "UA",
        "GOVUK FTA URL": "https://www.gov.uk/government/collections/uk-ukraine-political-free-trade-and-strategic-partnership-agreement",
        "Mendel agreement label": "EU-AGR-SIGNED-NO-LINK",
        "TWUK content template label": "EU-AGR-SIGNED-NO-LINK",
    }
]


def update_trade_scenarios(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    for item in trade_data:
        country_code = item["Country code"]
        trade_scenario = item["TWUK content template label"]
        content_url = item["GOVUK FTA URL"]

        try:
            country = Country.objects.get(country_code=country_code)
        except Country.DoesNotExist:
            logging.error("Could not find country with country_code=%s", country_code)
        else:
            country.scenario = trade_scenario
            country.content_url = content_url
            country.save()


class Migration(migrations.Migration):

    dependencies = [("countries", "0004_auto_20201021_1041")]

    operations = [
        migrations.RunPython(update_trade_scenarios, migrations.RunPython.noop)
    ]
