# Generated by Django 2.2.13 on 2020-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_auto_20201119_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='has_eu_trade_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='has_uk_trade_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
