# Generated by Django 2.2.13 on 2020-12-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_auto_20201214_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_eu',
            field=models.BooleanField(default=False),
        ),
    ]
