# Generated by Django 2.2.13 on 2020-12-24 10:41

import csv
import logging
import os

from django.db import migrations

from . import DATA_DIR


def y_or_n(val):
    return val == "Y"


def update_trade_scenarios(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    csv_file_path = os.path.join(DATA_DIR, "trade-scenarios-2020-12-24.csv")
    with open(csv_file_path) as csv_data:
        reader = csv.DictReader(csv_data)

        updated_country_codes = []
        for row in reader:
            country_code = row["Country code"]
            try:
                country = Country.objects.get(country_code=country_code)
            except Country.DoesNotExist:
                logging.warning("Country %s does not exist", country_code)
                continue

            country.content_url = row["GOVUK FTA URL"]
            country.scenario = row["TWUK content template label"]
            country.has_uk_trade_agreement = y_or_n(row["UK has agreement"])
            country.has_eu_trade_agreement = y_or_n(row["EU has agreement"])
            country.save()

            updated_country_codes.append(country_code)

        not_updated_countries = Country.objects.exclude(country_code__in=updated_country_codes).values_list("country_code", flat=True)
        logging.warning("Did not update %s", list(not_updated_countries))


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_set_is_eu'),
    ]

    operations = [
        migrations.RunPython(
            update_trade_scenarios,
            migrations.RunPython.noop,
        )
    ]
