# Generated by Django 2.2.19 on 2021-04-06 09:58

from django.db import migrations

GSP_COUNTRIES = [
    # Least Developed countries Framework
    "AF",
    "AO",
    "BD",
    "BJ",
    "BT",
    "BF",
    "BI",
    "CF",
    "KH",
    "TD",
    "KM",
    "CD",
    "DJ",
    "ER",
    "ET",
    "GN",
    "GW",
    "HT",
    "KI",
    "LA",
    "LS",
    "LR",
    "MG",
    "MW",
    "ML",
    "MR",
    "MZ",
    "MM",
    "NP",
    "NE",
    "RW",
    "ST",
    "SN",
    "SL",
    "SB",
    "SO",
    "SS",
    "SD",
    "TZ",
    "TG",
    "TV",
    "UG",
    "VU",
    "YE",
    "ZM",
    # Enhanced Framework
    "AM",
    "BO",
    "CV",
    "KG",
    "MN",
    "PK",
    "PH",
    "LK",
]

GSP_WITH_EXCLUSIONS_COUNTRIES = [
    "DZ",
    "CG",
    "CK",
    "IN",
    "ID",
    "FM",
    "NG",
    "NU",
    "SY",
    "TJ",
    "UZ",
]

SCENARIOS = [
    (GSP_COUNTRIES, "GSP"),
    (GSP_WITH_EXCLUSIONS_COUNTRIES, "GSP_WITH_EXCLUSIONS"),
    (["GH"], "EU_AGR_SIGNED_LINK"),
    (["JO"], "JORDAN"),
    (["VN"], "VIETNAM"),
]

URLS = {
    "GH": "https://www.gov.uk/government/collections/uk-ghana-interim-trade-partnership-agreement",
}


def update_trade_scenarios(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    for countries, scenario in SCENARIOS:
        for country_code in countries:
            country = Country.objects.get(country_code=country_code)
            country.scenario = scenario
            if country_code in URLS:
                country.content_url = URLS[country_code]
            country.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0014_update_trade_scenarios_2021_03_08"),
    ]

    operations = [
        migrations.RunPython(
            update_trade_scenarios,
            migrations.RunPython.noop,
        )
    ]
