# Generated by Django 2.2.20 on 2021-04-29 12:29

from django.db import migrations


def update_trade_scenario(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    cameroon = Country.objects.get(country_code="CM")
    cameroon.scenario = "EU_AGR_SIGNED_LINK"
    cameroon.content_url = "https://www.gov.uk/government/collections/uk-cameroon-economic-partnership-agreement"
    cameroon.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0015_update_trade_scenarios_2021_04_06"),
    ]

    operations = [
        migrations.RunPython(
            update_trade_scenario,
            migrations.RunPython.noop,
        )
    ]
