# Generated by Django 2.2.24 on 2021-08-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0016_update_cameroon_trade_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="alternative_non_trade_country_code",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
