# Generated by Django 2.2.24 on 2021-08-09 07:20

from django.db import migrations


def add_serbia_alternative_country_code(apps, schema_editor):
    Country = apps.get_model("countries", "Country")
    serbia = Country.objects.get(country_code="XS")
    serbia.alternative_non_trade_country_code = "RS"
    serbia.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0017_country_alternative_non_trade_country_code"),
    ]

    operations = [
        migrations.RunPython(
            add_serbia_alternative_country_code,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
