# Generated by Django 2.2.24 on 2021-09-06 14:09

from django.db import migrations


def update_trade_agreements(apps, schema_editor):
    Country = apps.get_model("countries", "Country")
    serbia = Country.objects.get(country_code="XS")
    serbia.scenario = "SERBIA"
    serbia.content_url = "https://www.gov.uk/government/collections/uk-serbia-partnership-trade-and-cooperation-agreement"
    serbia.has_uk_trade_agreement = True
    serbia.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0018_serbia_alternative_country_code"),
    ]

    operations = [
        migrations.RunPython(
            update_trade_agreements,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
