# Generated by Django 2.2.24 on 2021-09-07 14:01

from django.db import migrations


def update_trade_agreements(apps, schema_editor):
    Country = apps.get_model("countries", "Country")
    albania = Country.objects.get(country_code="AL")
    albania.scenario = "ALBANIA"
    albania.content_url = "https://www.gov.uk/government/collections/uk-albania-partnership-trade-and-cooperation-agreement"
    albania.has_uk_trade_agreement = True
    albania.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0019_auto_20210906_1509"),
    ]

    operations = [
        migrations.RunPython(
            update_trade_agreements,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
