# Generated by Django 2.2.24 on 2021-09-07 14:07

from django.db import migrations


def update_trade_agreements(apps, schema_editor):
    Country = apps.get_model("countries", "Country")
    ghana = Country.objects.get(country_code="GH")
    ghana.scenario = "GHANA"
    ghana.content_url = "https://www.gov.uk/government/collections/uk-ghana-interim-trade-partnership-agreement"
    ghana.has_uk_trade_agreement = True
    ghana.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0020_auto_20210907_1501"),
    ]

    operations = [
        migrations.RunPython(
            update_trade_agreements,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
