# Generated by Django 2.2.24 on 2021-09-24 15:04
import csv
import os
import logging

from django.db import migrations, models

from . import DATA_DIR


def update_countries_trade_scenarios(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    csv_file_path = os.path.join(DATA_DIR, "trade-scenario-reclassify-2021-09.csv")
    # register_countries = {}
    with open(csv_file_path) as country_scenarios_file:
        reader = csv.DictReader(country_scenarios_file)

        updated_country_names = []
        for row in reader:
            country_name = row["name"]
            try:
                country = Country.objects.get(name=country_name)
            except Country.DoesNotExist:
                logging.warning("Country %s could not be found in the DB", country_name)
                continue

            country.new_scenario = row["new_scenario"]
            country.trade_agreement_title = row["trade_agreement_title"]
            country.trade_agreement_type = row["trade_agreement_type"]
            country.new_trade_agreement_url = row["new_trade_agreement_url"]
            country.save()

            updated_country_names.append(country.name)

        not_updated_countries = Country.objects.exclude(
            name__in=updated_country_names
        ).values_list("name", flat=True)
        if not_updated_countries:
            logging.warning(
                "Did not update the following countries: %s",
                list(not_updated_countries),
            )


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0021_auto_20210907_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="new_scenario",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="new_trade_agreement_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="trade_agreement_title",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="trade_agreement_type",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.RunPython(
            update_countries_trade_scenarios, migrations.RunPython.noop
        ),
    ]
