# Generated by Django 2.2.24 on 2021-10-06 13:02

from django.db import migrations


def update_san_marino_trade_agreement_details(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    san_marino = Country.objects.get(country_code="SM")
    san_marino.trade_agreement_title = "UK/EU and EAEC: Trade and Cooperation Agreement"
    san_marino.new_trade_agreement_url = "https://www.gov.uk/government/publications/ukeu-and-eaec-trade-and-cooperation-agreement-ts-no82021"
    san_marino.save()


def reset_san_marino_trade_agreement_details(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    san_marino = Country.objects.get(country_code="SM")
    san_marino.trade_agreement_title = ""
    san_marino.new_trade_agreement_url = ""
    san_marino.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0022_auto_20210924_1604"),
    ]

    operations = [
        migrations.RunPython(
            update_san_marino_trade_agreement_details,
            reset_san_marino_trade_agreement_details,
        ),
    ]
