# Generated by Django 2.2.24 on 2021-10-07 09:49

from django.db import migrations


UPDATE_TO_FALSE = ["KE"]

UPDATE_TO_TRUE = ["AM", "KM", "SB", "WS"]


def update_eu_trade_agreement_status(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    for country_code in UPDATE_TO_FALSE:
        country = Country.objects.get(country_code=country_code)
        country.has_eu_trade_agreement = False
        country.save()

    for country_code in UPDATE_TO_TRUE:
        country = Country.objects.get(country_code=country_code)
        country.has_eu_trade_agreement = True
        country.save()


def reset_eu_trade_agreement_status(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    for country_code in UPDATE_TO_FALSE:
        country = Country.objects.get(country_code=country_code)
        country.has_eu_trade_agreement = True
        country.save()

    for country_code in UPDATE_TO_TRUE:
        country = Country.objects.get(country_code=country_code)
        country.has_eu_trade_agreement = False
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0023_auto_20211006_1402"),
    ]

    operations = [
        migrations.RunPython(
            update_eu_trade_agreement_status,
            reset_eu_trade_agreement_status,
        ),
    ]
