# Generated by Django 2.2.24 on 2021-10-15 07:05

from django.db import migrations


def update_trade_agreements(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    country_codes = ["GH", "JO"]

    for country in Country.objects.filter(country_code__in=country_codes):
        country.scenario = "TRADE_AGREEMENT_GSP_TRANS"
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0026_auto_20211011_1123"),
    ]

    operations = [
        migrations.RunPython(update_trade_agreements, migrations.RunPython.noop),
    ]
