# Generated by Django 2.2.24 on 2021-12-14 15:21
import csv
import os
import logging

from django.db import migrations, models

from . import DATA_DIR


def update_countries_guidance_urls(apps, schema_editor):
    # Get the full list of Rule-Of-Origin guidance URLS and store them in the countries DB table
    Country = apps.get_model("countries", "Country")

    csv_file_path = os.path.join(DATA_DIR, "rules_of_origin_guidance_urls.csv")

    with open(csv_file_path) as guidance_urls_file:
        reader = csv.DictReader(guidance_urls_file)

        for row in reader:
            country_name = row["name"]
            try:
                country = Country.objects.get(name=country_name)
            except Country.DoesNotExist:
                logging.warning("Country %s could not be found in the DB", country_name)
                continue

            country.roo_guidance_url = row["roo_guidance_url"]
            country.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0027_auto_20211015_0805"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="roo_guidance_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(update_countries_guidance_urls, migrations.RunPython.noop),
    ]
