# Generated by Django 2.2.24 on 2021-12-14 15:21
from django.db import migrations

from . import DATA_DIR


def update_au_nz_free_trade_details(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    # Update Australia details
    au_details = Country.objects.get(country_code="AU")
    au_details.content_url = (
        "https://www.gov.uk/government/collections/uk-australia-free-trade-agreement"
    )
    au_details.trade_agreement_title = "UK-Australia Free Trade Agreement"
    au_details.trade_agreement_type = "Free trade agreement"
    au_details.roo_guidance_url = (
        "https://www.gov.uk/government/collections/uk-australia-free-trade-agreement"
    )
    au_details.save()

    # Update New Zealand details
    nz_details = Country.objects.get(country_code="NZ")
    nz_details.content_url = (
        "https://www.gov.uk/government/collections/uk-new-zealand-free-trade-agreement"
    )
    nz_details.trade_agreement_title = "UK-New Zealand Free Trade Agreement"
    nz_details.trade_agreement_type = "Free trade agreement"
    nz_details.roo_guidance_url = (
        "https://www.gov.uk/government/collections/uk-new-zealand-free-trade-agreement"
    )
    nz_details.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0028_country_roo_guidance_url"),
    ]

    operations = [
        migrations.RunPython(
            update_au_nz_free_trade_details, migrations.RunPython.noop
        ),
    ]
