from trade_tariff_service.tts_api import COMMODITY_DETAIL_TABLE_KEYS

TABLE_COLUMN_TITLES = [tup[1] for tup in COMMODITY_DETAIL_TABLE_KEYS]

IMPORT_MEASURE_GROUPS = {
    "Tariffs and charges": (
        ("National duties - VAT", ("305", "VTA", "VTE", "VTS", "VTZ")),
        (
            "National duties - excise",
            (
                "306",
                "DAA",
                "DAB",
                "DAC",
                "DAE",
                "DAI",
                "DBA",
                "DBB",
                "DBC",
                "DBE",
                "DBI",
                "DCA",
                "DCC",
                "DCE",
                "DCH",
                "DDA",
                "DDB",
                "DDC",
                "DDD",
                "DDE",
                "DDF",
                "DDG",
                "DDJ",
                "DEA",
                "DFA",
                "DFB",
                "DFC",
                "DGC",
                "DHA",
                "DHC",
                "DHE",
                "EAA",
                "EAE",
                "EBA",
                "EBB",
                "EBE",
                "EBJ",
                "EDA",
                "EDB",
                "EDE",
                "EDJ",
                "EEA",
                "EEF",
                "EFA",
                "EFJ",
                "EGA",
                "EGB",
                "EGJ",
                "EHI",
                "EIA",
                "EIB",
                "EIC",
                "EID",
                "EIE",
                "EIJ",
                "EXA",
                "EXB",
                "EXC",
                "EXD",
                "FAA",
                "FAE",
                "FAI",
                "FBC",
                "FBG",
                "LAA",
                "LAE",
                "LBA",
                "LBB",
                "LBE",
                "LBJ",
                "LDA",
                "LEA",
                "LEF",
                "LFA",
                "LGJ",
            ),
        ),
        (
            "International duty",
            ("103", "105", "106", "112", "115", "117", "119", "141", "142", "145"),
        ),
        ("Agricultural duty", ("488", "489", "490", "651", "652", "653", "654")),
        (
            "Trade remedy",
            ("551", "552", "553", "554", "555", "561", "564", "565", "566", "570"),
        ),
        ("Safeguards and retaliation", ("695", "696")),
        ("Supplementary unit", ("109", "110")),
    ),
    "Quotas": (("Quotas", ("122", "123", "146", "147")),),
    "Other measures": (
        (
            "Prohibitions and restrictions (or other)",
            (
                "277",
                "278",
                "410",
                "420",
                "465",
                "467",
                "473",
                "474",
                "475",
                "476",
                "478",
                "479",
                "705",
                "706",
                "707",
                "708",
                "709",
                "710",
                "711",
                "712",
                "713",
                "714",
                "715",
                "716",
                "717",
                "718",
                "719",
                "722",
                "724",
                "725",
                "728",
                "730",
                "735",
                "740",
                "745",
                "746",
                "747",
                "748",
                "749",
                "750",
                "751",
                "755",
                "760",
                "761",
                "774",
                "AHC",
                "AIL",
                "ATT",
                "CEX",
                "COE",
                "COI",
                "CVD",
                "EQC",
                "HOP",
                "HSE",
                "PHC",
                "PRE",
                "PRT",
                "QRC",
            ),
        ),
        ("Credibility checks", ("430", "431", "481", "482", "483")),
    ),
}


def get_nomenclature_group_measures(nomenclature_model, group_name, country_code):
    group_measure_type_ids = [
        item
        for collection in [group[1] for group in IMPORT_MEASURE_GROUPS[group_name]]
        for item in collection
    ]
    return [
        measure
        for measure in nomenclature_model.tts_obj.get_import_measures(country_code)
        if measure.type_id in group_measure_type_ids
    ]
