# ~/.circleci/config.yml
version: 2
jobs:
  unit_tests:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    resource_class: medium
    working_directory: /tmp/app
    steps:
      - checkout
      - run:
          name: Run tests
          command: docker-compose -f docker-compose-circleci.yml up --exit-code-from helpdesk
      - store_test_results:
          path: /tmp/app/test-reports/

  format_and_secrets_checks:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: pip install pre-commit
      - restore_cache:
          keys:
            - pre-commit-cache-{{ arch }}-{{ .Branch }}
      - run:
          name: Formatting checks
          command: pre-commit run --from-ref origin/HEAD --to-ref HEAD
      - save_cache:
          key: pre-commit-cache-{{ arch }}-{{ .Branch }}
          paths:
            - ~/.cache/pre-commit

# CircleCI workflows
workflows:
  version: 2
  helpdesk:
    jobs:
      - unit_tests
      - format_and_secrets_checks
