# ~/.circleci/config.yml
version: 2
jobs:
  unit_tests:
    docker:
      - image: circleci/python:3.7
        environment:
          DEBUG: True
          DJANGO_SECRET_KEY: DJANGO_SECRET_KEY
          DJANGO_SETTINGS_MODULE: config.settings.test
          DJANGO_BASE_DIR: /app
          DIT_HELPDESK_ADMIN_PASSWORD: DIT_HELPDESK_ADMIN_PASSWORD
          DJANGO_POSTGRES_HOST: DJANGO_POSTGRES_HOST
          DJANGO_POSTGRES_DATABASE: DJANGO_POSTGRES_DATABASE
          DJANGO_POSTGRES_USER: DJANGO_POSTGRES_USER
          DJANGO_POSTGRES_PASSWORD: DJANGO_POSTGRES_PASSWORD
          DJANGO_POSTGRES_PORT: DJANGO_POSTGRES_PORT
          ALLOWED_HOSTS: 127.0.0.1,localhost
          RESTRICT_ADMIN: True
          ALLOWED_ADMIN_IPS: 127.0.0.1,
          ALLOWED_ADMIN_IP_RANGES: 127.0.0.1/32,
          LOGIN_URL: LOGIN_URL
          LOGIN_REDIRECT_URL: LOGIN_REDIRECT_URL
          IP_SAFELIST_XFF_INDEX: IP_SAFELIST_XFF_INDEX
          APP_START_DOMAIN: /choose-country/
          LOG_LEVEL: INFO
          DIRECTORY_CLIENT_CORE_CACHE_EXPIRE_SECONDS: 0
          DIRECTORY_CLIENT_CORE_CACHE_LOG_THROTTLING_SECONDS: 0
          SENTRY_ENVIRONMENT: docker-development
          SENTRY_DSN: SENTRY_DSN
          FEEDBACK_EMAIL: FEEDBACK_EMAIL
          FEEDBACK_CONTACT: FEEDBACK_CONTACT
          DEFRA_EMAIL: DEFRA_EMAIL
          DEFRA_CONTACT: DEFRA_CONTACT
          BEIS_EMAIL: BEIS_EMAIL
          BEIS_CONTACT: BEIS_CONTACT
          DDAT_CONTACT: "DDAT Support Team"
          DIT_CONTACT: "DIT EU Exit Team"
          CONTACT_SUBJECT: "New UK Trade Helpdesk enquiry"
          FEEDBACK_SUBJECT: "UK Trade Helpdesk feedback"
          SERVICE_NAME: "twuk"
          DIT_SUBDOMAIN: "dit"
          DIT_SUBJECT_SUFFIX: " - DIT EU Exit Enquiries"
          DDAT_SUBJECT_SUFFIX: " - DDAT Support Team"
          HMRC_TAX_FORM_URL: HMRC_TAX_FORM_URL
          HELPDESK_GA_GTM: HELPDESK_GA_GTM
          QUOTA_DEFAULT_MESSAGE: "You can check the availability of this quota by contacting the relevant department."
          TEST_OUTPUT_DIR: "./test-reports/"
          FEEDBACK_DESTINATION_EMAIL: going@to.com
      - image: circleci/postgres:10
        name: postgres
        environment:
          POSTGRES_DB: helpdesk
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        name: es
        environment:
          ES_URL: http://es:9200
          discovery.type: single-node
      - image: redis:3.2.10
        environment:
          REDIS_URL: "redis://localhost:6379/"
    working_directory: /tmp/app
    steps:
      - checkout
      - run:
          name: Install system deps
          command: sudo apt-get update && sudo apt-get install -y graphviz libgraphviz-dev nodejs npm
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v2-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv install --system --dev
      - save_cache:
          key: v2-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/venv
      - run:
          name: Webpack build
          command: npm install && npm run build
      - run:
          name: Running tests
          command: coverage run manage.py test dit_helpdesk --settings=config.settings.test
      - run:
          name: Generate coverage
          command: |
            coverage report
            coverage html -d ./test-reports/coverage_html
      - run:
          name: Lint migrations
          command: ./lint_migrations.sh
      - run:
          name: flake8 lint check
          command: flake8
      - run:
          name: Python code formatting check
          command: black ./dit_helpdesk --check
      - run:
          name: Javascript code formatting check
          command: npx prettier assets/javascript --check
      - run:
          name: eslint check
          command: npx eslint assets/javascript
      - run:
          name: stylelint check
          command: npx stylelint assets/scss
      - store_test_results:
          path: ./test-reports/
      - store_artifacts:
          path: ./test-reports/coverage_html

# CircleCI workflows
workflows:
  version: 2
  helpdesk:
    jobs:
      - unit_tests
