# ~/.circleci/config.yml
version: 2
jobs:
  unit_tests:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    working_directory: /tmp/app
    steps:
      - checkout
      - run:
          name: Run tests
          command: docker-compose -f docker-compose-circleci-unit-tests.yml up --exit-code-from helpdesk
      - store_test_results:
          path: /tmp/app/test-reports/
      - store_artifacts:
          path: /tmp/app/test-reports/
      - run:
          name: Prepare coverage report
          command: |
            mkdir -p unit-coverage
            cp /tmp/app/test-reports/unit_tests/coverage.xml unit-coverage/coverage.xml
      - persist_to_workspace:
          root: ~/
          paths:
            - 'project/unit-coverage/*'

  format_and_secrets_checks:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: pip install pre-commit
      - restore_cache:
          keys:
            - pre-commit-cache-{{ arch }}-{{ .Branch }}
      - run:
          name: Formatting checks
          command: pre-commit run --from-ref origin/HEAD --to-ref HEAD
      - save_cache:
          key: pre-commit-cache-{{ arch }}-{{ .Branch }}
          paths:
            - ~/.cache/pre-commit

  server_up:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    working_directory: /tmp/app
    steps:
      - checkout
      - run:
          name: Run server
          command: docker-compose -f docker-compose-circleci-server-up.yml up --exit-code-from checkserver

# CircleCI workflows
workflows:
  version: 2
  helpdesk:
    jobs:
      - unit_tests
      - format_and_secrets_checks
      - server_up
