# ~/.circleci/config.yml
version: 2
aliases:
  - &redis_version              redis:3.2.10
  - &postgres_version           circleci/postgres:10
  - &elasticsearch_version      docker.elastic.co/elasticsearch/elasticsearch:6.4.3
  - &python_version             circleci/python:3.6
  - &kibana_version             docker.elastic.co/kibana/kibana:6.4.3

  - &unit_base_envs
    DEBUG: True
    DJANGO_SECRET_KEY: DJANGO_SECRET_KEY
    DJANGO_SETTINGS_MODULE: config.settings.test
    DJANGO_BASE_DIR: /app
    DIT_HELPDESK_ADMIN_PASSWORD: DIT_HELPDESK_ADMIN_PASSWORD
    DJANGO_POSTGRES_HOST: DJANGO_POSTGRES_HOST
    DJANGO_POSTGRES_DATABASE: DJANGO_POSTGRES_DATABASE
    DJANGO_POSTGRES_USER: DJANGO_POSTGRES_USER
    DJANGO_POSTGRES_PASSWORD: DJANGO_POSTGRES_PASSWORD
    DJANGO_POSTGRES_PORT: DJANGO_POSTGRES_PORT

  - &ui_test_base_envs
    ADMIN_ENABLED: True
    DEBUG: True
    DISABLE_COLLECTSTATIC: 1
    DJANGO_SECRET_KEY: DJANGO_SECRET_KEY
    DJANGO_SETTINGS_MODULE: config.settings.docker_development
    DJANGO_BASE_DIR: /app
    DIT_HELPDESK_ADMIN_PASSWORD: DIT_HELPDESK_ADMIN_PASSWORD
    DJANGO_POSTGRES_HOST: DJANGO_POSTGRES_HOST
    DJANGO_POSTGRES_DATABASE: DJANGO_POSTGRES_DATABASE
    DJANGO_POSTGRES_USER: DJANGO_POSTGRES_USER
    DJANGO_POSTGRES_PASSWORD: DJANGO_POSTGRES_PASSWORD
    DJANGO_POSTGRES_PORT: DJANGO_POSTGRES_PORT

  # Redis container
  - &docker_redis
    image: *redis_version
    environment:
      REDIS_URL: "redis://localhost:6379/"

  # Postgres container
  - &docker_postgres
    image: *postgres_version
    name: postgres
#    password: test_db_psswd
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_HOST_AUTH_METHOD: trust

  # Elasticsearch container
  - &docker_elasticsearch
    image: *elasticsearch_version
    name: es
    environment:
      ES_URL: http://es:9200

  # Kibana container
  - &docker_kibana
    image: *kibana_version
    environment:
      ELASTICSEARCH_URL: http://es:9200
    ports: "5601:5601"

  # Python container
  - &docker_python
    image: *python_version

  # Helpdesk test container
  - &docker_helpdesk_test
    image: ukti/dit-helpdesk-test:1.0.0

  # Step for ui test* jobs
  - &wait_for_backend
    run:
      name: Wait for backend
      command: dockerize -wait http://localhost:8000/choose-country/ -timeout 300s

jobs:
  unit_tests:
    docker:
      - <<: *docker_python
        environment: *unit_base_envs
      - *docker_postgres
      - *docker_elasticsearch
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            coverage run manage.py test dit_helpdesk --settings=config.settings.test
      - run:
          name: Generate coverage
          command: |
            . venv/bin/activate
            coverage report
            coverage xml -o test-reports/coverage.xml
            coverage html -d test-reports/coverage_html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  ui_tests:
    docker:
      - <<: *docker_helpdesk_test
        environment: *ui_test_base_envs
      - *docker_postgres
      - *docker_elasticsearch
      - *docker_redis
      - *docker_kibana
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/development.txt
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
          paths:
            - "venv"
      - run:
          name: Start app
          command: |
            . venv/bin/activate
            ./compose/automation/django/start.sh
          background: true
      - *wait_for_backend
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            export PATH=$PATH:$HOME/bin
            pytest ui_test/specs
      - store_artifacts:
          path: screenshots


# CircleCI workflows
workflows:
  version: 2
  helpdesk:
    jobs:
      - unit_tests
      - ui_tests
