# Generated by Django 2.2.13 on 2021-02-12 14:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deferred_save', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deferredsave',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
