# Generated by Django 2.2.13 on 2021-02-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('deferred_changes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='deferred_change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='deferred_changes.DeferredChange'),
        ),
    ]
