# Generated by Django 2.1.5 on 2019-03-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='tts_number_indents',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='tts_section_position',
        ),
    ]
