# Generated by Django 2.2.13 on 2020-09-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0007_auto_20200908_1750'),
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='nomenclature_tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarchy.NomenclatureTree'),
        ),
    ]
