# Generated by Django 2.1.5 on 2019-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_auto_20190301_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='number_indents',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='parent_goods_nomenclature_item_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='parent_goods_nomenclature_sid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='parent_productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='productline_suffix',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
