# Generated by Django 2.1.5 on 2019-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_auto_20190310_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
