# Generated by Django 2.2.13 on 2020-09-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0010_auto_20200910_1650'),
        ('commodities', '0004_auto_20200908_2043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commodity',
            unique_together={('commodity_code', 'goods_nomenclature_sid', 'nomenclature_tree')},
        ),
    ]
