# Generated by Django 2.1.5 on 2019-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0004_auto_20190507_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='keyword',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
