# Generated by Django 2.1.5 on 2019-05-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0005_commodity_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='ranking_score',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
