# Generated by Django 2.1.5 on 2019-05-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0006_commodity_ranking_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='ranking_score',
            new_name='ranking',
        ),
    ]
