# Generated by Django 2.2.13 on 2020-10-05 16:20
import django_migration_linter as linter

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0006_auto_20200910_1650'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='commodity',
            name='tts_json',
        ),
    ]
