# Generated by Django 2.2.13 on 2020-10-06 12:18
import django_migration_linter as linter

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("commodities", "0007_remove_commodity_tts_json")]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(model_name="commodity", name="last_updated"),
    ]
