# Generated by Django 2.2.13 on 2020-10-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0007_remove_commodity_tts_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='last_updated',
        ),
    ]
