# Generated by Django 2.2.2 on 2019-08-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0008_auto_20190603_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='tts_heading_json',
        ),
    ]
