# Generated by Django 2.2.2 on 2019-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0009_remove_commodity_tts_heading_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='number_indents',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='parent_goods_nomenclature_item_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='parent_goods_nomenclature_sid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='parent_productline_suffix',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='productline_suffix',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='tts_is_leaf',
            field=models.BooleanField(),
        ),
    ]
