# Generated by Django 2.2.2 on 2019-08-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
