# Generated by Django 2.2.13 on 2021-02-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("deferred_changes_tests", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="deferred_changes_tests.ParentModel",
            ),
        )
    ]
