# Generated by Django 2.2.2 on 2019-09-11 06:33
import django_migration_linter as linter

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("contact", "0001_initial")]

    operations = [linter.IgnoreMigration(), migrations.DeleteModel(name="Contact")]
