# Generated by Django 2.1.5 on 2019-03-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0003_auto_20190314_1528'),
        ('hierarchy', '0003_auto_20190314_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('title', models.TextField(null=True)),
                ('celex', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.Commodity')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Section')),
            ],
        ),
    ]
