# Generated by Django 2.1.5 on 2019-03-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20190314_1528'),
        ('commodities', '0003_auto_20190314_1528'),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='section',
        ),
        migrations.AddField(
            model_name='regulation',
            name='commodities',
            field=models.ManyToManyField(to='commodities.Commodity'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='sections',
            field=models.ManyToManyField(to='hierarchy.Section'),
        ),
    ]
