# Generated by Django 2.1.5 on 2019-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_auto_20190319_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('celex', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='celex',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='url',
        ),
    ]
