# Generated by Django 2.1.5 on 2019-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_auto_20190319_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='regulations',
            field=models.ManyToManyField(to='regulations.Regulation'),
        ),
    ]
