# Generated by Django 2.2.13 on 2020-09-23 15:20
import django_migration_linter as linter

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_auto_20200923_1138'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RenameModel(
            old_name='Document',
            new_name='Regulation',
        ),
        migrations.AlterModelOptions(
            name='regulation',
            options={},
        ),
    ]
