# Generated by Django 2.1.5 on 2019-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20190314_1528'),
        ('regulations', '0005_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='chapters',
            field=models.ManyToManyField(to='hierarchy.Chapter'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='headings',
            field=models.ManyToManyField(to='hierarchy.Heading'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='subheadings',
            field=models.ManyToManyField(to='hierarchy.SubHeading'),
        ),
    ]
