# Generated by Django 2.2.13 on 2020-10-07 17:33

from django.db import migrations


def fill_regulations_nomenclature_tree(apps, schema_editor):

    RegulationGroup = apps.get_model('regulations', 'RegulationGroup')
    Regulation = apps.get_model('regulations', 'Regulation')
    NomenclatureTree = apps.get_model('hierarchy', 'NomenclatureTree')

    active_tree = NomenclatureTree.objects.filter(
        region='EU',
        end_date__isnull=True,
    ).latest('start_date')

    unfilled_reg_groups = RegulationGroup.objects.filter(nomenclature_tree__isnull=True)
    unfilled_reg_groups.update(nomenclature_tree=active_tree)

    unfilled_regs = Regulation.objects.filter(nomenclature_tree__isnull=True)
    unfilled_regs.update(nomenclature_tree=active_tree)


def unfill_regulations_nomenclature_tree(apps, schema_editor):
    RegulationGroup = apps.get_model('regulations', 'RegulationGroup')
    Regulation = apps.get_model('regulations', 'Regulation')
    NomenclatureTree = apps.get_model('hierarchy', 'NomenclatureTree')

    active_tree = NomenclatureTree.objects.filter(
        region='EU',
        end_date__isnull=True,
    ).latest('start_date')

    filled_reg_groups = RegulationGroup.objects.filter(nomenclature_tree=active_tree)
    filled_reg_groups.update(nomenclature_tree=None)

    filled_regs = Regulation.objects.filter(nomenclature_tree=active_tree)
    filled_regs.update(nomenclature_tree=None)


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0005_auto_20201007_1833'),
    ]

    operations = [
        migrations.RunPython(
            fill_regulations_nomenclature_tree, unfill_regulations_nomenclature_tree
        )
    ]
