# Generated by Django 2.1.5 on 2019-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_auto_20190410_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'regulation document', 'verbose_name_plural': 'regulations documents'},
        ),
        migrations.AlterModelOptions(
            name='regulation',
            options={'verbose_name_plural': 'regulations'},
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='headings',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='sections',
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='title',
            field=models.TextField(),
        ),
    ]
