# Generated by Django 2.1.5 on 2019-05-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_auto_20190514_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
