# Generated by Django 2.2.2 on 2019-08-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0010_auto_20190806_1351'),
        ('regulations', '0008_auto_20190515_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='headings',
            field=models.ManyToManyField(to='hierarchy.Heading'),
        ),
    ]
