# Generated by Django 2.2.2 on 2019-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0009_regulation_headings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='title',
            field=models.TextField(),
        ),
    ]
