# Generated by Django 2.1.5 on 2019-04-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('hierarchy', '0003_auto_20190314_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('working_or_processing_one', models.TextField(blank=True, null=True)),
                ('working_or_processing_two', models.TextField(blank=True, null=True)),
                ('commodity_code', models.CharField(max_length=20)),
                ('is_exclusion', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_of_origin', to='hierarchy.Chapter')),
                ('parent_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rules_of_origin.Rule')),
            ],
            options={
                'verbose_name_plural': 'rules of origin',
            },
        ),
        migrations.CreateModel(
            name='RulesDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('source_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'rules of origin documents',
            },
        ),
        migrations.CreateModel(
            name='RulesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rules_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_of_origin.RulesDocument')),
            ],
            options={
                'verbose_name_plural': 'rules of origin',
            },
        ),
        migrations.CreateModel(
            name='RulesGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('rules_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_of_origin.RulesGroup')),
            ],
            options={
                'verbose_name_plural': 'rules of origin group members',
            },
        ),
        migrations.AddField(
            model_name='rulesdocument',
            name='rules_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_of_origin.RulesGroup'),
        ),
        migrations.AddField(
            model_name='rule',
            name='rules_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_of_origin.RulesDocument'),
        ),
    ]
