# Generated by Django 2.1.5 on 2019-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0002_rule_rule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='commodity_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rulesgroupmember',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rulesgroupmember',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
