# Generated by Django 2.1.5 on 2019-04-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0003_auto_20190403_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesgroup',
            name='rules_document',
        ),
    ]
