# Generated by Django 2.2.13 on 2020-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0003_auto_20200918_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesdocument',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
