# Generated by Django 2.2.13 on 2020-12-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0017_nomenclaturetree_source'),
        ('countries', '0005_auto_20201119_1450'),
        ('rules_of_origin', '0003_auto_20200918_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rule",
            new_name="OldRule",
        ),
        migrations.RenameModel(
            old_name="RuleItem",
            new_name="OldRuleItem",
        ),
        migrations.RenameModel(
            old_name="RulesDocument",
            new_name="OldRulesDocument",
        ),
        migrations.RenameModel(
            old_name="RulesGroup",
            new_name="OldRulesGroup",
        ),
        migrations.RenameModel(
            old_name="RulesGroupMember",
            new_name="OldRulesGroupMember",
        ),
        migrations.RenameModel(
            old_name="RulesDocumentFootnote",
            new_name="OldRulesDocumentFootnote",
        ),
        migrations.CreateModel(
            name='RulesDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),

                ('countries', models.ManyToManyField(related_name='rules_documents',
                                                     to='countries.Country')),
                ('description', models.TextField()),
                ('rule_text', models.TextField(blank=True, null=True)),
                ('alt_rule_text', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(null=True, blank=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'rules of origin documents',
                'unique_together': ('source_url',)
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(null=True, blank=True, max_length=255)),
                ('is_exclusion', models.BooleanField(default=False)),
                ('rules_document', models.ForeignKey(
                    "RulesDocument", on_delete=models.CASCADE, null=True, blank=True
                )),
                ('rule_text', models.TextField(null=True, blank=True)),
                ('alt_rule_text', models.TextField(null=True, blank=True)),
                ('chapters', models.ManyToManyField(
                    "hierarchy.Chapter",
                    related_name="rules_of_origin",
                )),
                ('headings', models.ManyToManyField(
                    "hierarchy.Heading",
                    related_name="rules_of_origin",
                )),
            ],
            options={
                'verbose_name_plural': 'rules of origin',
            },
        ),
        migrations.CreateModel(
            name='RulesDocumentFootnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('identifier', models.TextField(blank=True, null=True)),
                ('link_html', models.TextField(blank=True, null=True)),
                ('note', models.TextField()),
                ('rules_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rules_of_origin.RulesDocument')),
            ],
            options={
                'verbose_name_plural': 'rules document footnotes',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SubRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_text', models.TextField(blank=True, null=True)),
                ('alt_rule_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RenameField(
            model_name='oldrulesgroupmember',
            old_name='rules_group',
            new_name='old_rules_group',
        ),
        migrations.AlterUniqueTogether(
            name='oldrulesgroupmember',
            unique_together={('country', 'old_rules_group', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='rulesdocument',
            unique_together={('source_url',)},
        ),
        migrations.AddField(
            model_name='subrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_of_origin.Rule'),
        ),
        migrations.RenameField(
            model_name='oldrulesdocument',
            old_name='rules_group',
            new_name='old_rules_group',
        ),
        migrations.RenameField(
            model_name='oldrule',
            old_name='rules_document',
            new_name='old_rules_document',
        ),
        migrations.AlterUniqueTogether(
            name='oldrulesdocument',
            unique_together={('old_rules_group', 'source_url')},
        ),
    ]
