# Generated by Django 2.1.5 on 2019-04-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0004_remove_rulesgroup_rules_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesgroupmember',
            name='rules_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_of_origin.RulesGroup'),
        ),
    ]
