# Generated by Django 2.2.13 on 2020-11-17 12:33
import django_migration_linter as linter

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0016_remove_chapter_last_updated"),
        ("rules_of_origin", "0005_auto_20201117_1221"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(model_name="rule", name="chapter"),
        migrations.AddField(
            model_name="rule",
            name="chapters",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="rules_of_origin",
                to="hierarchy.Chapter",
            ),
        ),
    ]
