# Generated by Django 2.1.5 on 2019-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0005_auto_20190403_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
