# Generated by Django 2.1.5 on 2019-04-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0006_auto_20190403_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesgroup',
            name='description',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='rulesdocument',
            unique_together={('rules_group', 'source_url')},
        ),
    ]
