# Generated by Django 2.1.5 on 2019-04-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0007_auto_20190404_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='commodity_code',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='parent_rule',
        ),
    ]
