# Generated by Django 2.2.13 on 2020-11-17 16:42
import django_migration_linter as linter

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0007_auto_20201117_1626'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
