# Generated by Django 2.1.5 on 2019-04-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('rules_of_origin', '0008_auto_20190404_0413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rulesgroupmember',
            unique_together={('country', 'rules_group', 'start_date')},
        ),
    ]
