# Generated by Django 2.1.5 on 2019-04-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0009_auto_20190404_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesgroup',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
