# Generated by Django 2.1.5 on 2019-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0010_auto_20190404_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesdocument',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
