# Generated by Django 2.1.5 on 2019-04-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0011_auto_20190408_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesDocumentFootnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('link_html', models.TextField()),
                ('note', models.TextField()),
                ('rules_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='rules_of_origin.RulesDocument')),
            ],
            options={
                'verbose_name_plural': 'rules document footnotes',
            },
        ),
    ]
