# Generated by Django 2.1.5 on 2019-04-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0012_rulesdocumentfootnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
