# Generated by Django 2.1.5 on 2019-06-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0013_auto_20190417_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rulesgroupmember',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='rulesgroupmember',
            name='rules_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_of_origin.RulesGroup'),
        ),
        migrations.AlterField(
            model_name='rulesgroupmember',
            name='start_date',
            field=models.DateField(),
        ),
    ]
