# Generated by Django 2.2.13 on 2021-02-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rules_of_origin", "0017_auto_20210201_2038")]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="description_processed",
            field=models.TextField(blank=True, null=True),
        )
    ]
