# Generated by Django 2.2.13 on 2021-02-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_of_origin', '0018_rule_description_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrule',
            name='description_processed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
