# Generated by Django 2.2.24 on 2021-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_of_origin", "0019_subrule_description_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="hs_from",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="hs_from_type",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="hs_to",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="hs_to_type",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="code",
            field=models.CharField(max_length=255),
        ),
    ]
