# Generated by Django 2.2.24 on 2021-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_of_origin", "0020_auto_20211026_1407"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rule",
            old_name="is_exclusion",
            new_name="is_extract",
        ),
        migrations.AddField(
            model_name="rule",
            name="hs_type",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
