# Generated by Django 2.2.24 on 2021-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules_of_origin", "0020_auto_20211201_1432"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="chapters",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="commodities",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="headings",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="subheadings",
        ),
        migrations.RemoveField(
            model_name="rulesdocument",
            name="nomenclature_tree",
        ),
    ]
