# Generated by Django 2.2.24 on 2021-11-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules_of_origin", "0021_auto_20211111_1610"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="chapters",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="commodities",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="headings",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="subheadings",
        ),
        migrations.RemoveField(
            model_name="rulesdocument",
            name="nomenclature_tree",
        ),
    ]
