# Generated by Django 2.2.24 on 2021-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_of_origin", "0022_auto_20211115_1329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="code",
            field=models.CharField(max_length=255),
        ),
    ]
