# Generated by Django 2.2.24 on 2021-11-30 16:53

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace


def remove_periods(apps, schema_editor):
    Rule = apps.get_model("rules_of_origin", "Rule")

    Rule.objects.update(
        hs_from=Replace("hs_from", Value("."), Value("")),
        hs_to=Replace("hs_from", Value("."), Value("")),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("rules_of_origin", "0023_auto_20211126_1616"),
    ]

    operations = [
        migrations.RunPython(remove_periods, migrations.RunPython.noop),
    ]
