# Generated by Django 2.2.24 on 2021-11-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_of_origin", "0024_auto_20211130_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="hs_from",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="hs_to",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
