# Generated by Django 2.1.5 on 2019-01-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_documents', '0002_auto_20190121_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='heading_code_4',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='heading_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
