# Generated by Django 3.2.10 on 2021-12-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deferred_changes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deferredcreate",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="deferredupdate",
            name="data",
            field=models.JSONField(),
        ),
    ]
