# Generated by Django 2.2.13 on 2021-02-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deferred_changes', '0002_deferredupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deferredcreate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deferredupdate',
            options={},
        ),
    ]
